# Generated by Django 5.0.14 on 2026-09-30 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0002_campaign_enquiry_campaign'),
        ('members', '0006_restore_shepherds_from_newcomers'),
        ('newcomers', '0006_newcomer_keep_in_touch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey', models.CharField(choices=[('online', 'Online contacts'), ('newcomers', 'Newcomers'), ('converts', 'New converts'), ('any', 'Any journey')], max_length=12)),
                ('theme', models.CharField(max_length=60)),
                ('number', models.PositiveIntegerField(help_text='Its number within the theme, from 1.')),
                ('verse', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=60)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['journey', 'theme', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey', models.CharField(choices=[('online', 'Online contacts'), ('newcomers', 'Newcomers'), ('converts', 'New converts')], max_length=12)),
                ('day', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['journey', 'day'],
            },
        ),
        migrations.CreateModel(
            name='SavedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('done_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey', models.CharField(choices=[('online', 'Online contacts'), ('newcomers', 'Newcomers'), ('converts', 'New converts')], max_length=12)),
                ('started', models.DateField()),
                ('plan', models.CharField(choices=[('standard', 'Standard'), ('daily', 'Daily')], default='standard', max_length=10)),
                ('shift', models.PositiveIntegerField(default=0, help_text='Days added when a personal reply took a planned day.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped'), ('ended', 'Ended'), ('moved', 'Moved to another journey')], default='active', max_length=10)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='enquiries.enquiry')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='members.member')),
                ('newcomer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='newcomers.newcomer')),
            ],
            options={
                'ordering': ['-started', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('planned', 'Planned message'), ('own', 'Own message'), ('reply', 'Personal reply'), ('skipped', 'Skipped')], max_length=10)),
                ('theme', models.CharField(blank=True, default='', max_length=60)),
                ('text', models.TextField(blank=True, default='', help_text="Exactly what was sent, with WhatsApp's marks.")),
                ('on_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='followup.enrolment')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-on_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('journey', 'theme', 'number'), name='unique_message_number'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='followup.messagetemplate'),
        ),
        migrations.AddField(
            model_name='planstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_steps', to='followup.messagetemplate'),
        ),
        migrations.AddField(
            model_name='savedmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stepdone',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stepdone',
            name='enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_done', to='followup.enrolment'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('enquiry__isnull', True), ('member__isnull', True), ('newcomer__isnull', False)), models.Q(('enquiry__isnull', True), ('member__isnull', False), ('newcomer__isnull', True)), models.Q(('enquiry__isnull', False), ('member__isnull', True), ('newcomer__isnull', True)), _connector='OR'), name='enrolment_one_person'),
        ),
        migrations.AddConstraint(
            model_name='planstep',
            constraint=models.UniqueConstraint(fields=('journey', 'day'), name='unique_plan_day'),
        ),
        migrations.AddConstraint(
            model_name='stepdone',
            constraint=models.UniqueConstraint(fields=('enrolment', 'step'), name='unique_step_done'),
        ),
    ]
