# Generated by Django 5.0.14 on 2026-10-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_load_message_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
