# Generated by Django 5.0.14 on 2026-08-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(choices=[('Short-term', 'Short-term'), ('Medium-term', 'Medium-term'), ('Long-term', 'Long-term'), ('Spiritual growth', 'Spiritual growth')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current', models.DecimalField(decimal_places=2, default=0, help_text='Only meaningful for manual goals , auto goals compute live instead.', max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=10)),
                ('tracking', models.CharField(choices=[('auto', 'Auto-tracked'), ('manual', 'Manual')], max_length=10)),
                ('period_type', models.CharField(choices=[('month', 'This month'), ('quarter', 'This quarter'), ('year', 'This year'), ('none', 'Not time-boxed')], default='none', help_text='Batch 0.5, Finding 1: auto goals filter their underlying query to this window.', max_length=10)),
                ('source', models.CharField(help_text='Plain-language description shown to users.', max_length=300)),
                ('link_route', models.CharField(blank=True, default='', max_length=50)),
                ('link_tab', models.CharField(blank=True, default='', max_length=50)),
                ('calculation_type', models.CharField(blank=True, choices=[('latest_session_total', 'Latest filled session total'), ('task_completion_rate', 'Follow-up task completion rate'), ('testimony_count', 'Testimony count'), ('member_category_moves', 'Members moved to a category'), ('milestone_count', 'Milestone count')], default='', max_length=30)),
                ('calculation_target_category', models.CharField(blank=True, default='', help_text="Used by MEMBER_CATEGORY_MOVES, e.g. 'Worker'.", max_length=30)),
                ('calculation_meeting_type', models.ForeignKey(blank=True, help_text='Used by LATEST_SESSION_TOTAL.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.meetingtype')),
            ],
            options={
                'ordering': ['horizon', 'name'],
            },
        ),
    ]
