# Generated by Django 5.0.14 on 2026-08-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        ('newcomers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='calculation_milestone_type',
            field=models.ForeignKey(blank=True, help_text='Used by MILESTONE_COUNT.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newcomers.milestonetype'),
        ),
    ]
