# Generated by Django 5.0.14 on 2026-09-27 09:14

from django.db import migrations, models


def use_a_real_average(apps, schema_editor):
    """Goals named as a monthly average now calculate one. They used the
    latest single service. Only goals whose name says so are changed."""
    Goal = apps.get_model("goals", "Goal")
    for g in Goal.objects.filter(calculation_type="latest_session_total",
                                 name__icontains="(monthly avg)"):
        g.calculation_type = "monthly_average_attendance"
        if g.source.startswith("From the latest filled"):
            g.source = "Average per service this month, from the filled sessions."
        g.save(update_fields=["calculation_type", "source"])


def back_to_latest(apps, schema_editor):
    Goal = apps.get_model("goals", "Goal")
    Goal.objects.filter(calculation_type="monthly_average_attendance").update(
        calculation_type="latest_session_total")


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='calculation_type',
            field=models.CharField(blank=True, choices=[('latest_session_total', 'Latest filled session total'), ('monthly_average_attendance', 'Average attendance this month'), ('task_completion_rate', 'Follow-up task completion rate'), ('testimony_count', 'Testimony count'), ('member_category_moves', 'Members moved to a category'), ('milestone_count', 'Milestone count')], default='', max_length=30),
        ),
        migrations.RunPython(use_a_real_average, back_to_latest),
    ]
