# Generated by Django 5.0.14 on 2026-10-01 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='0 Sower up to 5 Good and Faithful Servant.')),
                ('since', models.DateField(help_text='When they reached this level.')),
                ('grace_until', models.DateField(blank=True, help_text='Below their level: they keep it until this date.', null=True)),
                ('moved_up_on', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_standing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
