# Generated by Django 5.0.14 on 2026-10-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestanding',
            name='note_dismissed_on',
            field=models.DateField(blank=True, help_text='When they last dismissed the dashboard note.', null=True),
        ),
    ]
