# Generated by Django 5.0.14 on 2026-08-15 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('target_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.location')),
            ],
            options={
                'ordering': ['-status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giving_entries', to='finance.fund')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giving_entries', to='core.location')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_entries', to='members.member')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giving_entries', to='finance.paymentmethod')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_entries', to='finance.project')),
            ],
            options={
                'verbose_name_plural': 'Giving',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('receipt_file', models.FileField(blank=True, help_text='Real uploaded file (Batch 2.8) , was a placeholder URL field until now.', null=True, upload_to='receipts/%Y/%m/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
