# Generated by Django 5.0.14 on 2026-09-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_fellowship_attendancesession_led_by_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giving',
            name='remitted_to',
            field=models.CharField(choices=[('retained', 'Retained in location account'), ('dubai', 'DLBC account, Dubai'), ('lagos', 'DLBC account, Lagos'), ('qatar', 'DLBC account, Qatar')], default='retained', max_length=20),
        ),
        migrations.AddField(
            model_name='giving',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving', to='attendance.attendancesession'),
        ),
    ]
