# Generated by Django 5.0.14 on 2026-09-26 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# The destinations recorded per giving entry in version 10. Version 11
# records remittance once a month instead, so the column goes. What was
# recorded is copied into the audit log first, one entry per giving that
# was marked as sent somewhere, so nothing entered is lost and a rollback
# can put it back.
ARCHIVE_ACTION = "Archived at version 11"
ARCHIVE_PREFIX = "Remitted to before version 11: "
DESTINATION_LABELS = {
    "dubai": "DLBC account, Dubai",
    "lagos": "DLBC account, Lagos",
    "qatar": "DLBC account, Qatar",
}


def archive_destinations(apps, schema_editor):
    Giving = apps.get_model("finance", "Giving")
    AuditLog = apps.get_model("accounts", "AuditLog")
    entries = []
    for g in Giving.objects.exclude(remitted_to="retained").select_related("fund"):
        label = DESTINATION_LABELS.get(g.remitted_to, g.remitted_to)
        entries.append(AuditLog(
            user=None,
            user_name_snapshot="System upgrade",
            action=ARCHIVE_ACTION,
            entity_type="Giving",
            # The id leads so the rollback can find the entry again.
            entity_name=f"#{g.id} {g.date} {g.fund.name} {g.amount}"[:200],
            details=f"{ARCHIVE_PREFIX}{g.remitted_to} ({label})",
        ))
    AuditLog.objects.bulk_create(entries, batch_size=500)


def restore_destinations(apps, schema_editor):
    """Rolling back puts each archived destination back on its entry."""
    Giving = apps.get_model("finance", "Giving")
    AuditLog = apps.get_model("accounts", "AuditLog")
    archived = AuditLog.objects.filter(action=ARCHIVE_ACTION, entity_type="Giving")
    for entry in archived:
        try:
            giving_id = int(entry.entity_name.split()[0].lstrip("#"))
            code = entry.details[len(ARCHIVE_PREFIX):].split()[0]
        except (IndexError, ValueError):
            continue
        Giving.objects.filter(id=giving_id).update(remitted_to=code)
    archived.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_giving_remitted_to_giving_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Must run before the column is removed.
        migrations.RunPython(archive_destinations, restore_destinations),
        migrations.RemoveField(
            model_name='giving',
            name='remitted_to',
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('sent_on', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, default='', help_text='Bank or transfer reference, so the record can be matched against a statement.', max_length=80)),
                ('note', models.TextField(blank=True, default='', help_text='Required when the amount sent differs from the amount due.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittances_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=3, max_digits=12)),
                ('amount_sent', models.DecimalField(decimal_places=3, max_digits=12)),
                ('destination', models.CharField(choices=[('dubai', 'Dubai'), ('lagos', 'Lagos'), ('qatar', 'Qatar'), ('kept', 'Kept here')], default='dubai', max_length=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_lines', to='finance.fund')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.remittance')),
            ],
            options={
                'ordering': ['fund__name'],
                'unique_together': {('remittance', 'fund')},
            },
        ),
    ]
