# Generated by Django 5.0.14 on 2026-09-27 08:42

import django.db.models.deletion
from django.db import migrations, models


def give_existing_a_location(apps, schema_editor):
    """Any remittance recorded before this belongs to the main location,
    which is the only one the old version could have meant."""
    Remittance = apps.get_model("finance", "Remittance")
    Location = apps.get_model("core", "Location")
    main = Location.objects.filter(is_core=True).first()
    if main:
        Remittance.objects.filter(location__isnull=True).update(location=main)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appsetting'),
        ('finance', '0003_remove_giving_remitted_to_remittance_remittanceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='core.location'),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='month',
            field=models.DateField(),
        ),
        migrations.RunPython(give_existing_a_location, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='remittance',
            unique_together={('month', 'location')},
        ),
    ]
