# Generated by Django 5.0.14 on 2026-08-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('is_core', models.BooleanField(default=False, help_text='True only for Bahrain. Prevents deletion.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
