# Generated by Django 5.0.14 on 2026-08-16 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpUrgencySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visiting', 'Visiting'), ('integrated', 'Integrated'), ('not-interested', 'Not Interested')], max_length=20, unique=True)),
                ('amber_days', models.PositiveIntegerField()),
                ('red_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewcomerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublicRegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('successful', models.BooleanField()),
                ('reason', models.CharField(choices=[('success', 'Success'), ('honeypot', 'Honeypot field triggered'), ('too_fast', 'Submitted faster than humanly possible'), ('rate_limited', 'Too many submissions from this IP'), ('invalid_data', 'Failed normal field validation')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Newcomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visiting', 'Visiting'), ('integrated', 'Integrated'), ('not-interested', 'Not Interested')], default='new', max_length=20)),
                ('created_at', models.DateField(help_text='First-contact date, set once and never changed.')),
                ('stage_since', models.DateField(help_text='Updates every time stage changes.')),
                ('not_interested_note', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('city_governorate', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
                ('age_group', models.CharField(blank=True, choices=[('under_20', 'Under 20'), ('20_and_above', '20 and above')], default='', max_length=15)),
                ('prayer_request', models.TextField(blank=True, default='')),
                ('is_first_timer', models.BooleanField(default=False)),
                ('is_new_resident', models.BooleanField(default=False)),
                ('wants_visit', models.BooleanField(default=False)),
                ('wants_to_know_more', models.BooleanField(default=False)),
                ('wants_salvation_info', models.BooleanField(default=False)),
                ('invited_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcomers_assigned', to=settings.AUTH_USER_MODEL)),
                ('invited_by_member', models.ForeignKey(blank=True, help_text='Auto-matched by exact name at creation time if unambiguous; invited_by_name is the durable record either way.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcomers_invited', to='members.member')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newcomers', to='core.location')),
                ('meeting_attended', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcomer_intakes', to='attendance.meetingtype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newcomers', to='newcomers.newcomersource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewcomerStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visiting', 'Visiting'), ('integrated', 'Integrated'), ('not-interested', 'Not Interested')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('newcomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='newcomers.newcomer')),
            ],
            options={
                'verbose_name_plural': 'Newcomer status history',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewcomerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('due_date', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, help_text="Batch 0.3, Finding 3: independent of the newcomer's primary leader; defaults to it if left blank at the application layer.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcomer_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('newcomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='newcomers.newcomer')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='NewcomerMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('milestone_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='newcomers.milestonetype')),
                ('newcomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='newcomers.newcomer')),
            ],
            options={
                'unique_together': {('newcomer', 'milestone_type')},
            },
        ),
    ]
