# Generated by Django 5.0.14 on 2026-08-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcomers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcomertask',
            name='contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcomertask',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('Home visit', 'Home visit'), ('Phone call', 'Phone call'), ('Text message', 'Text message'), ('Spoke after service', 'Spoke after service'), ('Other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='newcomertask',
            name='contact_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
