# Generated by Django 5.0.14 on 2026-09-07 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcomers', '0003_newcomertask_contact_goal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupurgencysetting',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('attending', 'Attending'), ('member', 'Member'), ('not-interested', 'Not Interested')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='newcomer',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('attending', 'Attending'), ('member', 'Member'), ('not-interested', 'Not Interested')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='newcomerstatushistory',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('attending', 'Attending'), ('member', 'Member'), ('not-interested', 'Not Interested')], max_length=20),
        ),
        migrations.CreateModel(
            name='NewcomerContactAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('Phone call', 'Phone call'), ('WhatsApp', 'WhatsApp'), ('Text message', 'Text message'), ('Social media message', 'Social media message'), ('Email', 'Email'), ('Home visit', 'Home visit')], max_length=30)),
                ('note', models.CharField(blank=True, default='', help_text='Anything worth knowing, for example whether a message was left.', max_length=300)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcomer_contact_attempts', to=settings.AUTH_USER_MODEL)),
                ('newcomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='newcomers.newcomer')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
