# Generated by Django 5.0.14 on 2026-08-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('day', models.CharField(blank=True, default='', max_length=20)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('occasional', 'Occasional')], max_length=20)),
                ('detail_level', models.CharField(choices=[('detailed', 'Detailed (Men/Women/Youth/Children)'), ('simple', 'Simple (Men/Women only)')], max_length=20)),
                ('monthly_target', models.PositiveIntegerField(blank=True, help_text='Applies regardless of frequency , Batch 0.2 decision.', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('in-person', 'In person'), ('online', 'Online')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled')], default='pending', max_length=10)),
                ('track_named', models.BooleanField(default=False)),
                ('men', models.PositiveIntegerField(default=0)),
                ('women', models.PositiveIntegerField(default=0)),
                ('youth_boys', models.PositiveIntegerField(default=0)),
                ('youth_girls', models.PositiveIntegerField(default=0)),
                ('children_boys', models.PositiveIntegerField(default=0)),
                ('children_girls', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='core.location')),
                ('meeting_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='attendance.meetingtype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='attendance.attendancesession')),
            ],
            options={
                'unique_together': {('session', 'member')},
            },
        ),
    ]
