# Generated by Django 5.0.14 on 2026-08-17 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesessionmember',
            name='checked_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendancesessionmember',
            name='mode',
            field=models.CharField(choices=[('in-person', 'In person'), ('online', 'Online')], default='in-person', help_text='Per-attendee, not per-session , a single hybrid service can correctly have some members in-person and others online.', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='counts_for_absence',
            field=models.BooleanField(default=False, help_text='If true, a member not checked into this meeting gets a real follow-up task created for their shepherd. Admin-configurable, not every meeting carries equal attendance expectation , confirmed design decision, defaults off except where explicitly enabled.'),
        ),
    ]
