# Generated by Django 5.0.14 on 2026-08-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesessionmember_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Used only for absence follow-up timing (counts_for_absence) , how the system knows a service has actually started and enough time has passed to treat an unchecked member as absent, not just not-arrived-yet. Optional: a meeting with counts_for_absence on but no start_time is simply never auto-checked until one is set.', null=True),
        ),
    ]
