# Generated by Django 5.0.14 on 2026-09-07 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_meetingtype_start_time'),
        ('members', '0004_member_from_newcomer_member_is_leader'),
        ('newcomers', '0004_alter_followupurgencysetting_stage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesessionmember',
            unique_together={('session', 'member')},
        ),
        migrations.AddField(
            model_name='attendancesessionmember',
            name='newcomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='newcomers.newcomer'),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('workers', 'Workers'), ('leadership', 'Leadership')], default='everyone', help_text='Who is expected at this meeting, and so who is followed up when absent.', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancesessionmember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesessionmember',
            unique_together={('session', 'member'), ('session', 'newcomer')},
        ),
    ]
