# Generated by Django 5.0.14 on 2026-09-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancesessionmember_unique_together_and_more'),
        ('members', '0004_member_from_newcomer_member_is_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='led_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_sessions', to='members.member'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='lesson',
            field=models.CharField(blank=True, default='', help_text='Which study was covered, for example "BTB 15".', max_length=60),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='new_comers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='new_converts',
            field=models.PositiveIntegerField(default=0, help_text='Gave their life to Christ at this meeting.'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='online_children_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='online_children_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='online_men',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='online_women',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='online_youth_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='online_youth_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='fellowship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='attendance.fellowship'),
        ),
    ]
