# Generated by Django 5.0.14 on 2026-09-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_fellowship_attendancesession_led_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowship',
            name='meeting_type',
            field=models.ForeignKey(blank=True, help_text='The meeting these fellowships hold, so one session is generated per fellowship per date.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fellowship_set', to='attendance.meetingtype'),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='collects_offering',
            field=models.BooleanField(default=False, help_text='Whether the session form asks for an offering. Set here rather than fixed in code, so the church can change it.'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='day',
            field=models.CharField(blank=True, default='', help_text='Full weekday name for a weekly meeting, or blank for an occasional one. Anything else generates no sessions.', max_length=20),
        ),
    ]
