# Generated by Django 5.0.14 on 2026-09-27 02:30

import django.db.models.deletion
from collections import Counter

from django.db import migrations, models


def set_locations(apps, schema_editor):
    """
    Give each fellowship the location its sessions were recorded at.

    A fellowship with no sessions yet is given the main location, since
    fellowships added before this point were the main church's. The
    preflight command lists every fellowship with its location so an
    administrator can confirm them.
    """
    Fellowship = apps.get_model("attendance", "Fellowship")
    AttendanceSession = apps.get_model("attendance", "AttendanceSession")
    Location = apps.get_model("core", "Location")

    locations = list(Location.objects.all())
    main = next((l for l in locations if l.is_core), None) or (
        locations[0] if len(locations) == 1 else None)

    for f in Fellowship.objects.filter(location__isnull=True):
        used = Counter(AttendanceSession.objects.filter(fellowship=f)
                       .values_list("location_id", flat=True))
        if used:
            Fellowship.objects.filter(pk=f.pk).update(location_id=used.most_common(1)[0][0])
        elif main is not None:
            Fellowship.objects.filter(pk=f.pk).update(location=main)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_v11_data'),
        ('core', '0002_appsetting'),
    ]

    operations = [
        # The field is added below, then filled in.
        migrations.AddField(
            model_name='fellowship',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location this fellowship belongs to. Blank for every location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fellowships', to='core.location'),
        ),
        migrations.RunPython(set_locations, migrations.RunPython.noop),
    ]
