# Generated by Django 5.0.14 on 2026-10-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_fellowship_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='edition_name',
            field=models.CharField(blank=True, default='', help_text='The theme or title of this edition, for an occasional meeting.', max_length=120),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='edition_place',
            field=models.CharField(blank=True, default='', help_text='Where this edition is held: the host city or venue.', max_length=120),
        ),
    ]
