# Generated by Django 5.0.14 on 2026-10-01 10:29

from django.db import migrations, models
from django.utils import timezone


def set_usual_modes(apps, schema_editor):
    """Kay: every meeting has people joining online, and only the Friday
    Worship Service also meets in person. Upcoming sessions not yet filled in
    follow their meeting. Sessions already recorded keep their mode."""
    MeetingType = apps.get_model("attendance", "MeetingType")
    Session = apps.get_model("attendance", "AttendanceSession")
    for mt in MeetingType.objects.all():
        both = mt.id == "fri-worship" or mt.name.strip().lower() == "friday worship service"
        mt.usual_mode = "in-person-and-online" if both else "online"
        mt.save(update_fields=["usual_mode"])
        Session.objects.filter(meeting_type=mt, status="pending", date__gte=timezone.localdate()).update(mode=mt.usual_mode)


def undo_modes(apps, schema_editor):
    """Rolling back: the old column holds only In person or Online, so a
    session held in person and online becomes In person, the nearest."""
    Session = apps.get_model("attendance", "AttendanceSession")
    Session.objects.filter(mode="in-person-and-online").update(mode="in-person")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_session_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='usual_mode',
            field=models.CharField(choices=[('in-person-and-online', 'In person and online'), ('online', 'Online'), ('in-person', 'In person')], default='online', help_text='How this meeting is usually held.', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='mode',
            field=models.CharField(choices=[('in-person', 'In person'), ('online', 'Online'), ('in-person-and-online', 'In person and online')], max_length=24),
        ),
        migrations.RunPython(set_usual_modes, undo_modes),
    ]
