# Generated by Django 5.0.14 on 2026-08-15 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testimonies', to='reports.service')),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_label', models.CharField(help_text='Display label, e.g. "04-10 Aug 2026"', max_length=50)),
                ('week_start', models.DateField(help_text='The real sortable/filterable date behind the label.')),
                ('highlights', models.TextField(blank=True, default='')),
                ('challenges', models.TextField(blank=True, default='')),
                ('prayer_points', models.TextField(blank=True, default='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_notes', to='reports.department')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('other_additions', models.TextField(blank=True, default='')),
                ('pdf_file', models.FileField(help_text='Local storage for now , Batch 2.8 swaps the storage backend to Azure Blob without changing this field.', upload_to='reports/%Y/%m/')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('period_month', 'period_year')},
            },
        ),
    ]
