# Generated by Django 5.0.14 on 2026-08-21 20:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newcomers', '0003_newcomertask_contact_goal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquirySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('social_handle', models.CharField(blank=True, default='', help_text='Their username on the platform they contacted us through.', max_length=150)),
                ('enquiry_text', models.TextField(blank=True, default='', help_text='What they asked about, in their words where possible.')),
                ('area', models.CharField(blank=True, default='', help_text='Where they are, if they said. May be outside Bahrain.', max_length=150)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('invited', 'Invited'), ('attended', 'Attended'), ('not-pursuing', 'Not pursuing')], default='new', max_length=20)),
                ('stage_since', models.DateField(default=django.utils.timezone.localdate)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('not_pursuing_note', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_assigned', to=settings.AUTH_USER_MODEL)),
                ('converted_newcomer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_enquiry', to='newcomers.newcomer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='enquiries.enquirysource')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-received_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('invited', 'Invited'), ('attended', 'Attended'), ('not-pursuing', 'Not pursuing')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='enquiries.enquiry')),
            ],
            options={
                'verbose_name_plural': 'Enquiry status history',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('due_date', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('contact_method', models.CharField(blank=True, choices=[('Phone call', 'Phone call'), ('WhatsApp', 'WhatsApp'), ('Social media message', 'Social media message'), ('Email', 'Email'), ('Home visit', 'Home visit'), ('Other', 'Other')], default='', max_length=30)),
                ('contact_goal', models.TextField(blank=True, default='')),
                ('contact_scripture', models.TextField(blank=True, default='')),
                ('contact_root_cause', models.TextField(blank=True, default='')),
                ('contact_next_step', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='enquiries.enquiry')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
