# Generated by Django 5.0.14 on 2026-08-24 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('spend', models.DecimalField(decimal_places=3, default=0, help_text='What was spent, in BHD. Zero for organic, unpaid pushes.', max_digits=10)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(blank=True, help_text='The platform this ran on, where it was a single platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='enquiries.enquirysource')),
            ],
            options={
                'ordering': ['-started_on', 'name'],
            },
        ),
        migrations.AddField(
            model_name='enquiry',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='enquiries.campaign'),
        ),
    ]
