# Generated by Django 5.0.14 on 2026-08-15 11:03

import django.db.models.deletion
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, default='', max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[members.models.validate_not_future, members.models.validate_not_implausibly_old])),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('category', models.CharField(choices=[('General Member', 'General Member'), ('Worker in Training', 'Worker in Training'), ('Worker', 'Worker')], default='General Member', max_length=30)),
                ('joined_date', models.DateField()),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.household')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.location')),
            ],
            options={
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberCategoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_category', models.CharField(choices=[('General Member', 'General Member'), ('Worker in Training', 'Worker in Training'), ('Worker', 'Worker')], max_length=30)),
                ('to_category', models.CharField(choices=[('General Member', 'General Member'), ('Worker in Training', 'Worker in Training'), ('Worker', 'Worker')], max_length=30)),
                ('changed_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_history', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'Member category history',
                'ordering': ['-changed_date'],
            },
        ),
    ]
