# Generated by Django 5.0.14 on 2026-08-17 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesessionmember_checked_in_at_and_more'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text="The worker responsible for this member's pastoral follow-up if they miss a tracked service. Same pattern as Newcomer.assigned_to.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_shepherded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemberFollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('due_date', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('missed_meeting_name', models.CharField(max_length=150)),
                ('missed_date', models.DateField()),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('contact_method', models.CharField(blank=True, choices=[('Home visit', 'Home visit'), ('Phone call', 'Phone call'), ('Text message', 'Text message'), ('Spoke after service', 'Spoke after service'), ('Other', 'Other')], default='', max_length=30)),
                ('contact_notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, help_text="Copied from the member's assigned shepherd at creation time , independent afterward, same pattern as NewcomerTask.assigned_to.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_followups_assigned', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='members.member')),
                ('missed_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_followups', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
