# Generated by Django 5.0.14 on 2026-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_assigned_to_memberfollowuptask'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfollowuptask',
            name='contact_goal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='memberfollowuptask',
            name='contact_next_step',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='memberfollowuptask',
            name='contact_root_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='memberfollowuptask',
            name='contact_scripture',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='memberfollowuptask',
            name='contact_notes',
            field=models.TextField(blank=True, default='', help_text='Legacy single-note field, kept so records created before the four structured fields existed still display correctly.'),
        ),
    ]
