# Generated by Django 5.0.14 on 2026-09-07 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_memberfollowuptask_contact_goal_and_more'),
        ('newcomers', '0004_alter_followupurgencysetting_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='from_newcomer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='became_member', to='newcomers.newcomer'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='Expected at leadership meetings. Independent of category.'),
        ),
    ]
